Step3
daihukumoshi/mercari-build-training pull request #2
Opened 2024-02-20 06:32 UTC by daihukumoshi

## What
# STEP3 商品一覧を取得する
```
 curl -X POST \
 --url 'http://localhost:9000/items' \
 -F 'name=jacket' \
 -F 'category=fashion' \
 -F 'image=@"/Users/mikikyouka/Downloads/local_image.jpg"'

{"message":"item received: jacket"}
```

# STEP4 画像を登録する
``` 
$ curl -X POST   --url "http://localhost:9000/items"   -F "name=jacket"   -F "category=fashion"   -F 'image=@"/Users/mikikyo
uka/Downloads/local_image.jpg"'
{"message":"item received: jacket"} 
```
json 
```
{"items":[{"name":"jacket","category":"fashion","image_name":"2d32c5a20662475a36c87332b4e52437011079b086589eaf991bf55b03393156.jpg"}]}
 ```

# STEP5 
```
$ curl -X GET 'http://127.0.0.1:9000/items/1'
{"name":"jacket","category":"fashion","image_name":"2d32c5a20662475a36c87332b4e52437011079b086589eaf991bf55b03393156.jpg"} 
```

# STEP6
ログレベルを変更するため、```c.Logger().Debugf("Image not found: %s", imgPath)```の一行上に以下のコードを追加しました。
```
c.Logger().SetLevel(log.DEBUG)
```
 ログ
  ```
images/no_image.jpg
{"time":"2024-02-20T15:28:09.049319+09:00","level":"DEBUG","prefix":"echo","file":"main.go","line":"159","message":"Image not found: images/no_image.jpg"}
{"time":"2024-02-20T15:28:09.04935+09:00","id":"","remote_ip":"127.0.0.1","host":"127.0.0.1:9000","method":"GET","uri":"/image/no_image.jpg","user_agent":"curl/7.79.1","status":404,"error":"code=404, message=Not Found","latency":96363,"latency_human":"96.363µs","bytes_in":0,"bytes_out":24} ```

2024-02-20 08:11 UTC, SuzuToyoda commented on go/app/main.go
> +	image_id := c.Param("image_id")
すごく細かい部分かもしれませんが関数名がGetItemなので、引数はImageIDよりもItemIDのほうが納得感があるかもしれません！ResourceOrientedという概念を調べて見たら参考になると思います

2024-02-20 08:11 UTC, SuzuToyoda commented on go/app/items.json
> +{"items":[{"name":"jacket","category":"fashion","image_name":""},{"name":"jacket","category":"fashion","image_name":"2d32c5a20662475a36c87332b4e52437011079b086589eaf991bf55b03393156.jpg"},{"name":"ja
これはgit add しなくてもいいと思います 👍 （あっても大丈夫です）

2024-02-20 09:19 UTC, NamikoToriyama requested changes
たくさんメッセージ送ってしまったんですが、よくできていたと思います。
修正お願いします🙇‍♀️

2024-02-20 09:19 UTC, NamikoToriyama commented on go/app/main.go
> +        fmt.Println("Read error")
ここでerrorが出た場合に、続きの処理をするとずっとエラーが出るのでエラーが出たらreturnするようにしましょう。他の部分も同様です。
```suggestion
        return err
```

または

```suggestion
        return fmt.Errorf("Read error: %v", err) // 勘で書いてるので構文間違ってたら直してください🙇‍♀️
```

ステータスコードを設定したいなら

```suggestion
        return c.JSON(http.StatusInternalServerError, Response{Message: err.Error()})
```

これでもいいです。errorの型を返すようにしてDebugできるようにしたいです。

2024-02-20 09:19 UTC, NamikoToriyama commented on go/app/main.go
> +	//}
[nits(直さなくてもok)] この部分は消していいと思います。

2024-02-20 09:19 UTC, NamikoToriyama commented on go/app/main.go
> +	var imageName string = fileName_hash + "." + extension
[nits] goで直接文字列を宣言する場合はこちらの記法を使うことの方が多いです。(好みの問題ですが)

```suggestion
	imageName := fileName_hash + "." + extension
```

2024-02-20 09:19 UTC, NamikoToriyama commented on go/app/main.go
> +	fmt.Println("アップロード成功!")
[nits] せっかく3-6でloggerの勉強をしているので、標準出力ではなくloggerを使ってもいいかもしれません。他の部分も同じです。

```suggestion
	c.Logger().Infof("アップロード成功!")
```

2024-02-20 09:19 UTC, NamikoToriyama commented on go/app/main.go
> +	index, _:= strconv.Atoi(image_id)
ここの _ にはerrorが入ってるので、errorハンドリングをしてください。

2024-02-20 09:19 UTC, NamikoToriyama commented on go/app/main.go
> +	}else {
[nits]
```suggestion
	} else {
```

2024-02-20 09:19 UTC, NamikoToriyama commented on go/app/main.go
> +}
[nits] このマークはファイルの最後が改行で終わってないマークなのでついてたら改行してみてください。今は起こる可能性は低いのですが、誤動作が起きるプログラムもあります

ref:
https://bottoms-programming.com/archives/indent-tab-space-and-new-line.html

2024-02-21 03:44 UTC, daihukumoshi commented
全て修正したつもりです🙇‍♀️
ResourceOrientedや最後の改行など知らなかったため非常に学びになります、ありがとうございます！

2024-02-21 04:08 UTC, NamikoToriyama commented on go/app/main.go
> +		return c.JSON(http.StatusOK, res)
[nits] ここはエラーを定義するのでもいいかもしれませんね。
```suggestion
		message := fmt.Sprintf("invalid item_id")
		res := Response{Message: message}
		return c.JSON(http.StatusBadRequest, res)
```

2024-02-21 04:09 UTC, NamikoToriyama approved these changes
とっても良いです！コードもすごく綺麗でいいともいます！

2024-02-21 08:50 UTC, merged